#! /bin/sh

sxhkd &
# prevent white screen on java apps
wmname compiz

monitors=$(xrandr --query | grep -c ' connected') 
# If more than 2 monitors are connected it fallsback to using only the primary monitor
if [ $monitors -eq 2 ];then
	# TODO remove monitor names hardcodings, retrieve names based on 'connected'
	# It works on my laptop, only display port is used for external monitor
	bspc monitor DP1 -d I II III IV V
	bspc monitor eDP1 -d VI VII VIII IX X
	# TODO center eDP1 under DP1
	# TODO remove resolution/refresh hardcodings
    	xrandr --output eDP1 --mode 1920x1080 --output DP1 --mode 3440x1440 --rate 50 --above eDP1
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# set background
if $(xdpyinfo | grep -q 1280x800); then
	feh --bg-center ~/images/wallpapers/thinkpad-x201/green_texture_1_1280x800.jpg
else
	feh --bg-center ~/images/wallpapers/workstation/darkpurple_landscape_1_2560x1080.jpg	
fi


bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
